import Head from 'next/head'
import Navigation from './Navigation'
import Container from 'react-bootstrap/Container'

export default function Layout({ children }) {
    return (
        <div>
            <Head>
                <title>Next Bootstrap Template</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navigation />

            <main className='mt-5'>
                <Container>
                    {children}
                </Container>
            </main>
        </div>
    )
}